# This is a basic workflow to help you get started with Actions

name: github checkout

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name : Run cp files
        run: sudo cp -RT ~/actions-runner/_work/action-tutorials/action-tutorials/ /var/www/html
