# This is a basic workflow to help you get started with Actions

name: github checkout

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Run pwd
        run: pwd
      - name: Run ls -al
        run: ls -al
      - name : Run cp files
        run: cp * /var/www/html
